jwt:
  algorithm: HS256
  expiration_minutes: 5
  issuer: watcher-service
  secret: ''
logger_service:
  retry_attempts: 3
  retry_delay: 5
  timeout: 10
  url_local: "http://localhost:5000/log"
  url_docker: "http://logger-service:5000/log"
logging:
  backup_count: 3
  file: logs/watcher-service.log
  level: INFO
  max_size_mb: 5
notifications:
  email:
    enabled: false
    from: watcher@example.com
    password: ''
    smtp_host: smtp.gmail.com
    smtp_port: 587
    to: admin@example.com
    use_tls: true
  syslog:
    enabled: false
    facility: local0
    host: localhost
    port: 514
service:
  name: watcher-service
watcher:
  check_interval: 1
  processed_directory: ../processed
  watch_directory: ../watched
  ignored_files:
    - .gitkeep
    - .gitignore
    - .DS_Store
    - Thumbs.db
    - desktop.ini