jwt:
  algorithm: HS256
  expiration_minutes: 5
  issuer: watcher-service
  secret: temp-key
logger_service:
  retry_attempts: 3
  retry_delay: 5
  timeout: 10
  url: http://localhost:5000/log
  url_docker: http://logger-service:5000/log
  url_local: http://localhost:5000/log
logging:
  backup_count: 5
  file: logs/watcher-service.log
  level: INFO
  max_size_mb: 5
notifications:
  email:
    enabled: true
    password: xclqyrjarfzvaavi
    to: default@example.com
  syslog:
    enabled: false
service:
  name: watcher-service
watcher:
  check_interval: 1
  ignored_files:
  - .gitkeep
  - .gitignore
  - .DS_Store
  - Thumbs.db
  - desktop.ini
  processed_directory: ../processed
  watch_directory: ../watched
