version: '3.8'

services:
  logger-service:
    build:
      context: ./logger-service
      dockerfile: Dockerfile
    container_name: logger-service
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/../logs
      - ./logger-service/logs:/app/logs
    environment:
      - JWT_SECRET=sasa-Software2015
      - LOGGER_HOST=0.0.0.0
      - LOGGER_PORT=5000
      - LOG_LEVEL=INFO
    networks:
      - jwt-file-system-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  watcher-service:
    build:
      context: ./watcher-service
      dockerfile: Dockerfile
    container_name: watcher-service
    depends_on:
      logger-service:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./watched:/app/watched
      - ./processed:/app/processed
      - ./watcher-service/logs:/app/logs
    environment:
      - JWT_SECRET=sasa-Software2015
      - LOGGER_URL=http://logger-service:5000/log
      - WATCH_DIR=/app/watched
      - PROCESSED_DIR=/app/processed
      - LOG_LEVEL=INFO
    networks:
      - jwt-file-system-network
    restart: unless-stopped

networks:
  jwt-file-system-network:
    driver: bridge