jwt:
  algorithm: HS256
  expected_issuer: watcher-service
  secret: '***hidden***'
logging:
  backup_count: 3
  file: logs/logger-service.log
  level: DEBUG
  max_size_mb: 5
notifications:
  email:
    enabled: true
    password: '***hidden***'
    smtp_host: smtp.gmail.com
    smtp_port: 587
    to: default@example.com
    use_tls: true
  syslog:
    enabled: false
service:
  debug: false
  host: 0.0.0.0
  name: logger-service
  port: 5000
storage:
  cleanup_enabled: true
  logs_directory: ../logs
  max_files: 3
