jwt:
  algorithm: HS256
  expected_issuer: watcher-service
  secret: sasa-Software2015
logging:
  backup_count: 5
  file: logs/logger-service.log
  level: WARN
  max_size_mb: 10
notifications:
  email:
    enabled: false
    from: logger@example.com
    password: ''
    smtp_host: smtp.gmail.com
    smtp_port: 587
    to: admin@example.com
    use_tls: true
  syslog:
    enabled: false
    facility: local0
    host: localhost
    port: 514
service:
  debug: false
  host: 0.0.0.0
  name: logger-service
  port: 5000
storage:
  cleanup_enabled: true
  logs_directory: ../logs
  max_files: 3
