service:
  name: logger-service
  host: 0.0.0.0
  port: 5000
  debug: false

jwt:
  secret: sasa-Software2015
  algorithm: HS256
  expected_issuer: watcher-service

storage:
  logs_directory: ../logs
  max_files: 1000
  cleanup_enabled: true

logging:
  level: INFO  # DEBUG | INFO | WARN | ERROR | FATAL
  file: logs/logger-service.log
  max_size_mb: 10
  backup_count: 5

notifications:
  email:
    enabled: false
    smtp_host: smtp.gmail.com
    smtp_port: 587
    use_tls: true
    from: logger@example.com
    to: admin@example.com
    password: ""  # Используйте переменную окружения EMAIL_PASSWORD

  syslog:
    enabled: false
    host: localhost
    port: 514
    facility: local0